apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "renku-ci-cleanup.fullname" . }}
  labels:
    {{- include "renku-ci-cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "renku-ci-cleanup.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
          serviceAccountName: {{ include "renku-ci-cleanup.serviceAccountName" . }}
          containers:
          - name: cleanup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - /bin/bash
            - /scripts/cleanup.sh
            env:
            {{- if .Values.cleanup.dryRun }}
            - name: DRY_RUN
              value: "true"
            {{- end }}
            volumeMounts:
            - name: cleanup-script
              mountPath: /scripts
              readOnly: true
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          volumes:
          - name: cleanup-script
            configMap:
              name: {{ include "renku-ci-cleanup.fullname" . }}-script
              defaultMode: 0755
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}