# Default values for renku-ci-cleanup
# This is a YAML-formatted file

# Container image configuration
image:
  repository: ghcr.io/wesjdj/renku-ci-cleanup
  pullPolicy: IfNotPresent
  tag: "latest"

# CronJob configuration
cronJob:
  # Cron schedule (every 6 hours by default)
  schedule: "0 */6 * * *"
  
  # Concurrency policy for the cronjob
  concurrencyPolicy: Forbid
  
  # Number of failed jobs to keep
  failedJobsHistoryLimit: 3
  
  # Number of successful jobs to keep
  successfulJobsHistoryLimit: 1
  
  # Restart policy for the job pods
  restartPolicy: OnFailure

# Cleanup configuration
cleanup:
  # Maximum age in hours for CI deployments before cleanup
  maxAge: 72
  
  # Label used to exempt namespaces from cleanup
  # Namespaces with this label will be skipped regardless of age
  exemptionLabel: "renku.io/cleanup-exempt=true"
  
  # Namespace name patterns to match (regex patterns)
  # Only namespaces matching these patterns will be considered for cleanup
  namespacePatterns:
    - "^renku-ci-.*"
  
  # Enable strict name pattern matching (default: true)
  # When true, namespaces must match at least one pattern to be cleaned up
  enforceNamePatterns: true
  
  # Dry run mode - set to true to only log what would be deleted
  dryRun: false

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  
  # Annotations to add to the service account
  annotations: {}
  
  # The name of the service account to use
  name: ""

# RBAC configuration
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity for pod assignment
affinity: {}

# Name overrides
nameOverride: ""
fullnameOverride: ""
